version: '3.1'

services:

  mongo:
    image: docker.io/library/mongo:5.0.15
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Test.123
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/volume

volumes:
  mongo-volume: {}